### ISSUE TITLE
FLEXManager returns null when i run the project in physical device

### ISSUE THREAD

**Issue by want17475186** [Flipboard/FLEX#144]
After the lunching of FLEX, the 'FLEX' button works well in the simulator. But when i use a physical device, there's nothing happened after i click the button. I find that FLEXManager alway returns null, any help?

**Comment by ryanolsonk** [comment]
My only guess here is that your project is set up to exclude FLEX in the builds that you are running on the device. However, I'm surprised that you're not getting build errors when referencing `FLEXManager`. Without more details, it's difficult to say what's going on. I have not seen reports of this before. I'm going to close since there's not currently anything actionable here.
