### ISSUE TITLE
App Rejected For Using 'className'

### ISSUE THREAD

**Issue by larryaasen** [Flipboard/FLEX#148]
We have apps that are getting rejected by the App Store for the use of className in our code, which is considered by Apple to be a non-public API. They mentioned this:

```
Our team has re-reviewed this app to ensure our findings were accurate, we found this app contains references to the following selectors:
className was found in the method [FLEXRealmDatabaseManager queryAllTables]
```

I found this line in the code:

```
66: if (objectSchema.className == nil) {
```

Would it be possible to update the class FLEXRealmDatabaseManager to eliminate the use of className?

Thanks,
Larry

**Comment by c0diq** [comment]
Also NSURLConnection is now deprecated when targeting iOS 9. Is there a way to add support to conditionally remove its usage?

**Comment by ryanolsonk** [comment]
Ironically, this call looks like private API use to Apple but it's actually not. However we do have some actual private API use (obfuscated) which is part of why we discourage shipping FLEX in app store builds. There are instructions in the README on how you can exclude it.

It could be nice to restructure the Realm integration as a subspec. That would keep the integration optional but properly include the Realm headers/library rather than doing things dynamically through the runtime for those that opt-in. If someone want's to look into that, I'd be happy to review, but it's not something I plan to take on personally.

For the separate `NSURLConnection` question, we've traditionally handled that in the project by suppressing the deprecation warnings via `#pragma clang diagnostic push ...` directives. I think there is enough lingering use of `NSURLConnection` that we don't actually want to remove the code.
