### ISSUE TITLE
When should it support macOS ?

### ISSUE THREAD

**Issue by michaelmou** [Flipboard/FLEX#156]
thanks your contribution..

**Comment by sietec** [comment]
I would love to see macos support also, is this planned?

If not, I may fork and modify for use with Mac but if you were planning this as a feature or new version, that would be great! Awesome tool, by the way!

**Comment by NSExceptional** [comment]
I don't think anyone is planning macOS support, feel free to give it a shot!

**Comment by sietec** [comment]
Thanks, I’m going to look into this now, especially since Mojave has a lot more iOS integrated into it, could make the (not so trivial) task easier!

**Comment by sietec** [comment]
I'm glad you closed this issue because i had completely forgotten about it until I saw the notice...I got sidetracked with other projects but I think I have time to look into this now. I know it's nice to keep issues tidy so I apologize that I got distracted from this!

No need to reopen, but feel free to contact me if you have any new ideas 💡  over the past few years 👍🏼

**Comment by SoCuul** [comment]
> I'm glad you closed this issue because i had completely forgotten about it until I saw the notice...I got sidetracked with other projects but I think I have time to look into this now. I know it's nice to keep issues tidy so I apologize that I got distracted from this!
> 
> No need to reopen, but feel free to contact me if you have any new ideas 💡 over the past few years 👍🏼

Hey! Did you ever manage to make any progress with a macOS port?
