### ISSUE TITLE
Instructions for how to use this in a Swift project

### ISSUE THREAD

**Issue by SimplGy** [Flipboard/FLEX#162]
This is very basic, I'm sorry, but I can't figure out how to do it.

I've included it in `Podfile`, run `pod install`:

    pod 'FLEX', '~> 2.4', :configurations => ['Debug']

And then tried:

* Running as-is in simulator. (doesn't show up, keyboard shortcuts `f` and `?` have no effect)
* Adding `#import <FLEX.h>` and `#import <FLEXManager.h>` to `Bridging-Header.h` (no change)
* Adding `import FLEXManager` or `import FLEXManager.h` to swift files (no such module)

**Comment by SimplGy** [comment]
I can do a PR that adds this to the readme if you'd like, once I figure it out.

**Comment by victorfigol** [comment]
@SimplGy did you figure it out? I have exactly the same problem!

**Comment by perteadrian** [comment]
Try `import FLEX`. For me, it worked.

**Comment by Mallox51** [comment]
Hi,

Here's what I did to have FLEX woking in a small swift 3.0 project :

Install cocoapods (if not alreday installed) and run `pod init` at root of project dir.
Update the `Podfile`, adding the line:

```
pod 'FLEX'
```

then run `pod install`

Open newly created `.xcworkspace` in XCode (instead of `.xcodeproj` file)

In XCode, _create a new file_, choose `Header File`. Name it `YourProjectName-Bridging-Header.h` for example. Then edit it and add the line :

```
#import <FLEX/FLEXManager.h>
```

Now open the _Build Settings_ of your project. Search for 'Objective-C Bridging Header' key (should appear in _'Swift Compiler - General section'_ and set value : `YourProjectName-Bridging-Header.h`

Command-Maj-K to clean projet. Then rebuild it.

In 'AppDelegate.swift' file, add 
```
import FLEX
```
then inside  `func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`

Add
```
 FLEXManager.shared().showExplorer()
```
which will launch FLEX on startup.

Hope it helps someone. 

Cheers

**Comment by brennantaylor** [comment]
If you link it as a `.framework` I don't think you need to bridge (just tried it on a pure swift project using Carthage). `import FLEX` worked as expected with just a link and copying the `.framework` during the build.

Also if you link it to your app and copy the `.framework` you get access to FLEX with no additional work in the simulator. Just hit one of the hotkeys.

**Comment by NSExceptional** [comment]
Closing this issue since we seem to have it figured out!
