### ISSUE TITLE
Suggestions or guidance for use with React Native

### ISSUE THREAD

**Issue by mcclen** [Flipboard/FLEX#195]
Has anyone given to consideration of whether and how to include something like Flex in a React Native app?

**Comment by brennantaylor** [comment]
Since an RN project is just an iOS project you should be able to open up the project file and link the framework into the app. Then it should work as expected.

This is an example of adding the library for linking and embedding it into the app using Carthage (I deleted my other frameworks to cut down on noise).

![image](https://user-images.githubusercontent.com/2840772/36438022-772d40ee-161d-11e8-9099-46749accf78d.png)


I don't know what the RN view hierarchy looks like but I believe it just renders various UIViews so the view debugging may work decently.

**Comment by fjtrujy** [comment]
I have create a bridge to be used in react-native projects (obviously just is working on iOS, but it is not throwing any error either android or web), so feel free to use it.

Also is published on `npm` repositories

https://github.com/fjtrujy/react-native-flipboard-flex

Thanks!
