### ISSUE TITLE
Add Device Log

### ISSUE THREAD

**Issue by docash59** [Flipboard/FLEX#24]
It'd be great and really useful if we could see all the device's logs. e.g. NSLogs etc.

**Comment by ryanolsonk** [comment]
Happy to say that I implemented this feature yesterday! Check out the latest master to see it. It uses the ASL C API to build a table view of the log messages. You can copy an individual message by long pressing on the cell, and you can filter the messages with a search term. It polls for updates and follows the log unless you scroll away from the bottom. Querying the ASL is a little slow in the simulator but reasonably fast on device. Luckily the main use case for this feature is on device since Xcode provides a much better console when working in the sim.

![screenshot 2015-01-26 10 55 55](https://cloud.githubusercontent.com/assets/1422245/5906150/468b82f8-a54a-11e4-86b6-b1e24fc2de7e.png)

![screenshot 2015-01-26 10 35 33](https://cloud.githubusercontent.com/assets/1422245/5906160/54dfd2dc-a54a-11e4-8f10-37e5acec106a.png)

![screenshot 2015-01-26 10 42 03](https://cloud.githubusercontent.com/assets/1422245/5906164/595e121a-a54a-11e4-81c3-263af95d8e10.png)

![screenshot 2015-01-26 10 42 17](https://cloud.githubusercontent.com/assets/1422245/5906165/5ecf5f74-a54a-11e4-8787-887a6ded9b15.png)

**Comment by JaviSoto** [comment]
WUT!? This is the most amazing thing ever. It works on iOS 7 and 8 too?

**Comment by ryanolsonk** [comment]
@JaviSoto thanks!

I hadn't actually tested it on iOS 7 until your comment. There was an interesting issue due to a mistake in the version of asl.h that comes with the iOS 8.1 SDK. It turned into a bit of a rabbit hole, but I think I've got everything worked out now. If you're curious, the commit is here: 063ffe97c1d256c341d522b9b9f95a6a7ee80e2c

**Comment by JaviSoto** [comment]
Great :) Sorry to give you work but I'm glad you figured it out!

**Comment by docash59** [comment]
Perfect, Thank you for implementing this into FLEX, very useful!

**Comment by jwardle** [comment]
Is the system log view only for log events that have been raised whilst the app is running? On my device it only seems to show since startup, and terminating the app has the effect of clearing the log. I'm using FLEX to debug an issue that occurs in the background and possibly across background -> termination and then later startup. It would be good to see the system log as a continuous flow across termination and startup. Is this possible?

**Comment by ryanolsonk** [comment]
FLEX uses the ASL API to query for log messages. It filters on the current process ID, which means it will not get messages from previous runs of the app.

More details on the ASL API here: https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/asl.3.html

And the FLEX method that fetches the log messages: https://github.com/Flipboard/FLEX/blob/master/Classes/GlobalStateExplorers/SystemLog/FLEXSystemLogTableViewController.m#L205-L235
