### ISSUE TITLE
FEATURE: CPU usabe and RAM Mem usage on Flex toggle

### ISSUE THREAD

**Issue by vincenzo-favara** [Flipboard/FLEX#288]
I would like to have the CPU usage and Ram usage in the little toggle when I just open flex.

**Comment by NSExceptional** [comment]
I personally feel this is out of the scope of FLEX, because this is something Xcode gives you when you debug your app. And if you're jailbroken, there are tweaks for this. But, feel free to make a PR! 

Additionally, you can add your own section to FLEX and display the information there yourself (see the demo app as an example on how to do this)
