### ISSUE TITLE
你好 有release 版吗?

### ISSUE THREAD

**Issue by MoShenGuo** [Flipboard/FLEX#355]
你好 有release版吗? 我可以打包时嵌入进去吗? 上面显示栏工具可以有代码控制吗?上面显示栏工具我可以用代码关闭和展示呢?谢谢

**Comment by NSExceptional** [comment]
English please

—
Tanner Bennett

**Comment by matrush** [comment]
No, you shouldn't release your app with FLEX compiled in. It should be used for internal debugging builds only. Apple won't accept apps built with FLEX AFAIK since it used some internal APIs and hacks.

You can fork the project and modify it locally to control what tools to show, that shouldn't be impossible.

Closing this issue for now.

**Comment by MoShenGuo** [comment]
I see, thank you
