### ISSUE TITLE
Inject FLEX in assistivetouchd

### ISSUE THREAD

**Issue by micodeyt** [Flipboard/FLEX#387]
Hello ! 
Do you have any clue how I could use FLEX to debug Assistive Touch UI elements ?

Thanks

**Comment by NSExceptional** [comment]
Hey! I was actually looking into this myself the other day…

I have no idea how to make it appear, I'm not sure what's wrong. I modified FLEXing so that it showed the toolbar on process launch and it still wouldn't appear for assistivetouchd. I guess I need to debug it and find out why FLEX doesn't appear.

**Comment by NSExceptional** [comment]
I'm going to move this to the actual FLEXing repo though, this is the wrong place for this issue.
