### ISSUE TITLE
Readme should cover test flight support

### ISSUE THREAD

**Issue by benlachman** [Flipboard/FLEX#53]
I can't tell from the read me whether there is a supported path for using FLEX with Apple TestFlight builds. Is this something that is even possible?

**Comment by ryanolsonk** [comment]
You can choose to include FLEX in any build you like. The README gives instructions on how to *exclude* FLEX from certain build configurations. For the configuration you use for TestFlight, simply ignore the exclusion instructions.

You *may* get rejected by beta app review because FLEX makes use of some private API. I've made an attempt to obfuscate all use of private API in a way that will make it through automated validation, but I don't know what will happen since I haven't tried uploading a build myself.

I would generally caution against using FLEX in beta builds, especially as you get close to the build you plan to submit. It's a good idea to have your beta builds be as close as possible to what you'll ultimately submit to avoid any nasty surprises. You almost certainly *do not* want to include FLEX in builds that you submit to the public App Store, as noted in the README.

I'm happy to answer more questions here, but I don't plan to add a dedicated TestFlight section to the README for now.
