### ISSUE TITLE
unset/remove NSUserDefaults value for NSDate

### ISSUE THREAD

**Issue by simonlinj** [Flipboard/FLEX#60]
There is no option to unset/remove value for a NSDate. 
![img_3017](https://cloud.githubusercontent.com/assets/1506890/7295386/ed095614-e9e7-11e4-9de4-e43a5f32ac84.PNG)

I also tried to call removeFromKey but crashed on the attempt 

![screen shot 2015-04-23 at 6 41 27 pm](https://cloud.githubusercontent.com/assets/1506890/7295465/ccb4ffd4-e9e8-11e4-99b9-4547598b3a89.png)

**Comment by ryanolsonk** [comment]
Did you use quotes around `dateKey` when calling `removeObjectForKey:`?

i.e.

![screenshot 2015-05-19 18 05 09](https://cloud.githubusercontent.com/assets/1422245/7717194/d90383dc-fe51-11e4-9fd4-9392ed8940e3.png)

Otherwise the input isn't valid JSON and will call `removeObjectForKey:` with `nil`, which throws an exception.

I agree it would be nice to have an unset button as part of the "Edit Default" screen. Contributions are always welcome :wink:.

**Comment by NSExceptional** [comment]
Closing this as there has been no response since 2015
