### ISSUE TITLE
Crasher in FLEXNetworkObserver

### ISSUE THREAD

**Issue by mickeyreiss** [Flipboard/FLEX#61]
I encountered an exception coming out of `+[FLEXNetworkObserver injectDidFinishLoadingIntoDelegateClass]`.

It seemed like my code managed to cause the `NSURLConnection` to release before the `connectionDidFinishLoading:delegate:` was called. As a result, `sniffWithoutDuplicationForObject:selector:sniffingBlock:` attempted to set an associated object on `nil`.

![image](https://cloud.githubusercontent.com/assets/47405/7336059/594c6de6-eb9d-11e4-9dcb-d25f082346d4.png)

Digging deeper, I noticed that my connection is `nil` as early as the call to the `implementationBlock`, which is swizzled in for `connectionDidFinishLoading:`. I'm not entirely unsurprised that my connection was released so early, as this connection represents a "fire and forget" analytics call.

![image](https://cloud.githubusercontent.com/assets/47405/7336044/7ba4cbdc-eb9c-11e4-8702-3153634701e5.png)

This is my current workaround, but I suspect someone who knows more about FLEX might be able to find an appropriate way for FLEX to hook in and hold a reference to the `NSURLConnection`:

```patch
diff --git i/Classes/Network/PonyDebugger/FLEXNetworkObserver.m w/Classes/Network/PonyDebugger/FLEXNetworkObserver.m
index 1dca18f..61eb2a4 100644
--- i/Classes/Network/PonyDebugger/FLEXNetworkObserver.m
+++ w/Classes/Network/PonyDebugger/FLEXNetworkObserver.m
@@ -680,11 +680,13 @@ didBecomeDownloadTask:(NSURLSessionDownloadTask *)downloadTask delegate:(id <NSU
     };
     
     NSURLConnectionDidFinishLoadingBlock implementationBlock = ^(id <NSURLConnectionDelegate> slf, NSURLConnection *connection) {
-        [self sniffWithoutDuplicationForObject:connection selector:selector sniffingBlock:^{
-            undefinedBlock(slf, connection);
-        } originalImplementationBlock:^{
-            ((void(*)(id, SEL, id))objc_msgSend)(slf, swizzledSelector, connection);
-        }];
+        if (connection) {
+            [self sniffWithoutDuplicationForObject:connection selector:selector sniffingBlock:^{
+                undefinedBlock(slf, connection);
+            } originalImplementationBlock:^{
+                ((void(*)(id, SEL, id))objc_msgSend)(slf, swizzledSelector, connection);
+            }];
+        }
     };
     
     [self replaceImplementationOfSelector:selector withSelector:swizzledSelector forClass:cls withMethodDescription:methodDescription implementationBlock:implementationBlock undefinedBlock:undefinedBlock];
```

Thanks!

**Comment by ryanolsonk** [comment]
Thanks for the detailed write up! I'll try to dig into this one tonight.

**Comment by ryanolsonk** [comment]
As you suggested, it seems like we have two options here:

1. Take the diff above which would avoid the crash but result in incomplete request history in some cases.
2. Keep a strong reference to the `NSURLConnection` in `FLEXInternalRequestState`. This would give us complete request history, but could also extend the lifetime of the `NSURLConnection` and potentially change the behavior of the underlying app.

I'm leaning towards 2 but I don't have a strong opinion either way. Any thoughts?

**Comment by mickeyreiss** [comment]
I think it would be acceptable to keep a reference to the `NSURLConnection`. In general, I don't think implementations should rely on particular reference count for any given object (but I suppose this could mask some subtle bugs). I'd lean towards option 2 as well.

**Comment by ryanolsonk** [comment]
@mickeyreiss I'm trying to reproduce this to understand the issue a little better. Could you tell me what version of AFNetworking you were using and what iOS version you were on when the crash occurred?

Thanks!

**Comment by intelliot** [comment]
I'm also encountering this issue. `Using AFNetworking (2.5.3)` but that may not be relevant in this case. I'm using `iphonesimulator` set to iPhone 6 running iOS Version 8.3 (SimulatorApp-565.9 CoreSimulator-117.15)

**Comment by ryanolsonk** [comment]
Great, thanks for the details. I'm going to try to repro with a similar setup.

**Comment by ryanolsonk** [comment]
I've finally gotten to the bottom of this one. It turns out it's unrelated to AFNetworking .

The PayPal SDK is making it's own call to the `-connectionDidFinishLoading:` method. This was especially tricky to track down because it does it via a call to `performSelector:afterDelay:withObject:` in `-[PPSimpleURLConnection initWithRequest:connectionTimeout:]`. It seems to be passing nil in the object argument, too. I knew something wasn't right when I saw `__NSFireDelayedPerform` on the stack trace rather than what you'd expect from URL loading system.

It's unfortunate that the PayPal SDK calls the delegate method itself, but we can avoid the crash by no-oping if the connection argument is nil. In the general case, if libraries are calling the `NSURLConnectionDelegate`  methods themselves, our request accounting will likely be inaccurate. It's worth noting that keeping a strong reference to the connection wouldn't've helped us here. 

Here's the `performSelector:withObject:afterDelay` trace

![screenshot 2015-05-23 14 17 55](https://cloud.githubusercontent.com/assets/1422245/7785842/abad3706-0159-11e5-970e-5157dc861d51.png)

I'm working on a change to fix the crash and should have something up shortly. /cc @mickeyreiss @intelliot

**Comment by ryanolsonk** [comment]
Ok! Please check out a42af79040d6506eb431a04b8cf9d45f0f8c0ffa and let me know if it works out for you.
