### ISSUE TITLE
iOS 8.3 endless recursive call on [FLEXExplorerViewController supportedInterfaceOrientations]

### ISSUE THREAD

**Issue by simonlinj** [Flipboard/FLEX#64]
This behaviour happens on real phone and simulator. but only on iOS 8.3.

Steps to reproduce: 
* Enable Flex
* Test an ActionsSheet or AlertView (no crash)
* Test an ActionsSheet or AlertView (crash)

Observations:
[UIApplication sharedApplication] keyWindow] is changed after the first iteration.

```
2015-05-12 14:33:57.028 UICatalog[50167:7492923] keyWindow: <UIWindow: 0x7fbc5171de80; frame = (0 0; 320 568); gestureRecognizers = <NSArray: 0x7fbc5171cd60>; layer = <UIWindowLayer: 0x7fbc5171ca70>>


2015-05-12 14:34:04.365 UICatalog[50167:7492923] keyWindow: <_UIAlertControllerShimPresenterWindow: 0x7fbc517238e0; frame = (0 0; 320 568); opaque = NO; gestureRecognizers = <NSArray: 0x7fbc5171a6f0>; layer = <UIWindowLayer: 0x7fbc51710700>>
```

![screen shot 2015-05-12 at 2 04 17 pm](https://cloud.githubusercontent.com/assets/1506890/7580955/d8956c32-f8af-11e4-9089-36bcf4ef21b0.png)

**Comment by simonlinj** [comment]
I just found out that this issue is a duplicate of #59 sorry!

but c38b90ee60d2ea9131a01b3e1a7014848e0494c9 doesn't solve the crash

**Comment by ryanolsonk** [comment]
Interesting. c38b90e fixed presenting one alert at a time, but I never thought to try presenting two alerts at the same time. I think your proposed change makes sense, but I'd like to dig into the system logic there to better understand the flow. Thanks for reporting the issue and for the pull request!

**Comment by simonlinj** [comment]
actually, its not presenting two alerts at the same time. but presenting one, close it. then open it again.
the weird thing is that it only happens on iOS 8.3

**Comment by ryanolsonk** [comment]
Oh, sorry I misunderstood. Does it reproduce for you in the example app? I just presented & closed several alerts there with FLEX presented and didn't get a crash (8.3 iPhone 6 simulator).

**Comment by simonlinj** [comment]
Hi sorry for the confusion.. The c38b90e solve the AlertView crash but not the ActionSheets crash. both on simulator and real device

**Comment by ryanolsonk** [comment]
Got it, thanks for the clarification. I started digging into this and the issue is a little deeper. When action sheets are presented on iOS 8.3, their host window (a `_UIAlertControllerShimPresenterWindow`) becomes key. This does not appear to happen with alert views.

When the action sheet is dismissed, the system looks for a new key window, basically taking the top visible window that's not a system window. As you noticed, that may be a `FLEXWindow` if FLEX is presented. We don't really want FLEX's window to become key when it is only showing the toolbar. The toolbar is intended to not interfere with anything in the app beneath it, so we want key events to go directly to the main app's windows.

The quickest fix is probably to prevent the `FLEXWindow` from becoming key when it is only showing the toolbar. I'll look at making that change now.

**Comment by ryanolsonk** [comment]
Ok, I've pushed f7c482ceedd539f225733faacb586c49b3247f39 with the change I mentioned above. The crash should be resolved for now.

Longer term, I may look at hosting the toolbar and the presented modals in separate windows. The toolbar window could declare itself as an internal window to prevent it from hijacking status bar appearance or becoming key. I think that would remove some of the hacks around trying to manage the key window.
