### ISSUE TITLE
Insert nil object into NSArray

### ISSUE THREAD

**Issue by Joride** [Flipboard/FLEX#82]
In FLEXNetworkTransactionTableViewCell.m around line 130 there is a nil date being inserted into an NSArray. 
It turns out self.transaction is nil (the setter is never called). This happens on iOS 9.0.2, not on iOS 8.

- (NSString *)transactionDetailsLabelText
{
    NSMutableArray *detailComponents = [NSMutableArray array];

    NSString *timestamp = [[self class] timestampStringFromRequestDate:self.transaction.startTime];
    [detailComponents addObject:timestamp];

.....

**Comment by bendytree** [comment]
I'm seeing the same thing. Just to expand a bit, the app crashes when I press "Network History" (on iOS 9.0.2). It was working on iOS 8.

It looks like `FLEXNetworkHistoryTableViewController` dequeues a `FLEXNetworkTransactionTableViewCell` then [sets the transaction](https://github.com/Flipboard/FLEX/blob/master/Classes/Network/FLEXNetworkHistoryTableViewController.m#L295). In iOS 9.0.2, it looks like `dequeueReusableCellWithIdentifier` actually calls `layoutSubviews` which means the transaction hasn't been set yet.  So I think a bunch of errors would happen because it tries to layout without a transaction.

Just to get it working again, I [added a nil check](https://github.com/bendytree/FLEX/commit/6eafd1944f8e0e45cfc1a1dafbd80aea61ea631d#diff-d16fd968ab04fb8eb9f23b8f366b2e91) at the beginning of `layoutSubviews`. Setting the transaction causes a re-layout, so this seems to work.

**Comment by ryanolsonk** [comment]
Sorry for the slow response time on this one. I couldn't repro on the 9.1 simulator or on my 9.1 iPhone 6, so hopefully that means the fixed the underlying issue. I added some nil safety in `FLEXNetworkTransactionTableViewCell` in b0b64c1ba9819fda4f004a71de7f6d5f7f7c8d2a to cover people still on 9.0.2.
