### ISSUE TITLE
When the scroll is decelerating in debug mode, I cannot press the navigation bar buttons.

### ISSUE THREAD

**Issue by Ricardo1980** [Flipboard/FLEX#87]
When the scroll is decelerating in debug mode, I cannot press the navigation bar buttons (right or left buttons).
Actually, the button changes to pressed state, and when the scroll stops, the action of the button is launched. It's very strange.
However, in release mode, it works perfectly.
Or if I remove FLEX from the debug version.

Any idea?

**Comment by ryanolsonk** [comment]
This sounds very strange indeed. Have you seen this behavior in the example project? I've never encountered it myself.

Do you have any additional details about simulator vs device, iOS version, etc.?

**Comment by Ricardo1980** [comment]
I could reproduce it in the sample app.

In AAPLAppDelegate.m, in didFinishLaunchingWithOptions add:

    UITapGestureRecognizer *tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:nil action:nil];
    tapRecognizer.numberOfTapsRequired = 4;
    [tapRecognizer addTarget:self action:@selector(handleGesture:)];
    [self.window addGestureRecognizer:tapRecognizer];

Add also this method there:

- (void)handleGesture:(UIGestureRecognizer *)gesture
{
    if (gesture.state == UIGestureRecognizerStateRecognized) {
        [[FLEXManager sharedManager] showExplorer];
    }
}

Launch the app in the simulator, move the scroll view and when is moving with the inertia, try for example to press the button at the top/right that says FLEX.  It will execute the action after the scroll stops.

**Comment by ryanolsonk** [comment]
Ah, thanks for providing the additional context.

It looks like this isn't actually related to FLEX, but to the 4-tap gesture recognizer that you attach to the window. You should see the same behavior if you remove FLEX entirely, but keep the gesture recognizer.

I'd suggest using a different gesture recognizer to trigger FLEX. You can use multiple touches rather than multiple taps to avoid conflicting with existing gestures in your app.

Let me know if this solves your issue.

**Comment by ryanolsonk** [comment]
Closing this issue since the gesture chosen to activate FLEX is not something this project has control over.
